---

server:
  servlet:
    context-path: /apis/v1
  port: 10001

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/example-app5
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true

logging:
  level:
    root: INFO
  org.hibernate: INFO

